FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Copiar proyecto y restaurar
COPY src/Pastebin.Client/Pastebin.Client.csproj src/Pastebin.Client/
RUN dotnet restore src/Pastebin.Client/Pastebin.Client.csproj

# Copiar todo y publicar
COPY . .
WORKDIR /src/src/Pastebin.Client
RUN dotnet publish -c Release -o /app/publish

# Stage Nginx
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/publish/wwwroot /usr/share/nginx/html
EXPOSE 80
EXPOSE 443
